# JULIA

In [1]:
# versioninfo
versioninfo()

Julia Version 1.10.1
Commit 7790d6f0641 (2024-02-13 20:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
Environment:
  JULIA_NUM_THREADS = 


In [2]:
Base.active_project()

"/Users/rene/Documents/Projects/Github/JuliaBasics/Project.toml"

## `minimim`, `maximum` and `extrema`

In [3]:
# fibonacci
vec = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

10-element Vector{Int64}:
  0
  1
  1
  2
  3
  5
  8
 13
 21
 34

In [4]:
# minimum, maximum
minimum(vec), maximum(vec)

(0, 34)

In [5]:
# maximum
extrema(vec)

(0, 34)

In [6]:
a = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [7]:
maximum(abs2, a, dims=1) # abs2 is 'squared absolute value'

1×2 Matrix{Int64}:
 9  16

In [8]:
minimum(abs2, a, dims=2) # abs2 is 'squared absolute value'

2×1 Matrix{Int64}:
 1
 9

In [9]:
minimum(length, ["Python", "Julia"])

5

## `findmin`, `findmax`

In [10]:
vec = [10, 50, 20, 40, 30]
findmin(-, vec)

(-50, 2)

In [11]:
vec = [π, 22/7, 3.14]
findmax(abs, vec)

(3.142857142857143, 2)

## `iseven`, `isodd`

In [12]:
iseven(10)

true

In [13]:
isodd.(1:5)

5-element BitVector:
 1
 0
 1
 0
 1

## `do`

In [14]:
map(1:5) do x
    2x # anonymous function
end

5-element Vector{Int64}:
  2
  4
  6
  8
 10

In [15]:
map(1:5, 10:10:50) do x, y
    x + y # anonymous function
end

5-element Vector{Int64}:
 11
 22
 33
 44
 55

## `map`

In [16]:
# map anonymous function
map(x->2x, 1:5)

5-element Vector{Int64}:
  2
  4
  6
  8
 10

In [17]:
# map anonymous function with multiple arguments
map((x, y) -> x+y, 1:5, 10:10:50)

5-element Vector{Int64}:
 11
 22
 33
 44
 55

In [18]:
# map function
map(sqrt, [1, 4, 9, 16, 25])

5-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0

In [19]:
# map function with multiple arguments
map(*, 1:5, 1:5)

5-element Vector{Int64}:
  1
  4
  9
 16
 25

## `try`, `catch`, `finally`

In [20]:
lines = try
    open("file.dat", "r") do f
        println(f, "Hello")
    end
catch
    @warn "Could not read file."
finally
    println("Finally!")
end

Finally!


┌ Warning: Could not read file.
└ @ Main /Users/rene/Documents/Projects/Github/JuliaBasics/base.ipynb:6


## `local`, `global`

In [21]:
function foo(n)
    x = 0
    for i = 1:n
        local x # introduce a loop-local x
        x = i
    end
    x
end

foo (generic function with 1 method)

In [22]:
foo(5)

0

In [23]:
z = 3

3

In [24]:
function foo()
    global z = 6 # use the z variable defined outside foo
end

foo (generic function with 2 methods)

In [25]:
foo()

6

## `const`

In [26]:
const p = 3.14

3.14

In [27]:
p = 3

ErrorException: invalid redefinition of constant Main.p

## `isa`

In [28]:
isa(100, Int)

true

In [29]:
100 isa Int

true

In [30]:
isa(100, AbstractFloat)

false

In [31]:
isa(100, Number)

true

## `isequal`


In [32]:
isequal(10, 10)

true

In [33]:
==(10, 10)

true

In [34]:
isequal(0.0, -0.0)

false

In [35]:
==(0.0, -0.0)

true

In [36]:
isequal(NaN, NaN)

true

In [37]:
==(NaN, NaN)

false

In [38]:
isequal(missing, missing)

true

In [39]:
==(missing, missing)

missing

## `isless`

In [40]:
isless(10, 20)

true

In [41]:
isless(20, 10)

false

In [42]:
isless("A", "B")

true

In [43]:
isless("B", "A")

false

## `typeassert`

In [44]:
typeassert(10, Int64)

10

In [45]:
typeassert(10, Float64)

TypeError: TypeError: in typeassert, expected Float64, got a value of type Int64

## `typeof`

In [46]:
typeof(100)

Int64

In [47]:
typeof("Julia")

String

In [48]:
typeof([1, 2.3])

Vector{Float64} (alias for Array{Float64, 1})

In [49]:
typeof([1, 'A'])

Vector{Any} (alias for Array{Any, 1})

## `objectid`

### mutable objects

In [50]:
x = [1, 2]; y = [1, 2];

In [51]:
objectid(x)

0xed1002612b9fd472

In [52]:
objectid(x) == objectid(y)

false

In [53]:
z = x
push!(z, 3)

3-element Vector{Int64}:
 1
 2
 3

In [54]:
objectid(x) == objectid(z)

true

### immutable objects

In [55]:
x = 1; y = 1;

In [56]:
objectid(x) == objectid(y)

true

In [57]:
objectid(z)

0xed1002612b9fd472

## `hash`

In [58]:
hash(10)

0x95ea2955abd45275

In [59]:
a = [1, 2]; b = [1, 2];

In [60]:
isequal(a, b)

true

In [61]:
hash(a) == hash(b)

true

## `Set`

In [62]:
Set("abcd")

Set{Char} with 4 elements:
  'a'
  'c'
  'd'
  'b'

In [63]:
Set("aaa")

Set{Char} with 1 element:
  'a'

In [64]:
s = Set([1, 2, 3, 4])
push!(s, 5)

Set{Int64} with 5 elements:
  5
  4
  2
  3
  1

In [65]:
s = Set([NaN, 0.0, 1.0, 2.0]);

In [66]:
1.0 in s

true

In [67]:
NaN in s # isequal(NaN, NaN) is true

true

In [68]:
-0.0 in s # isequal(0.0, -0.0) is false

false

## `union`

In [69]:
s1 = [1, 2]
s2 = [2, 3]
union(s1, s2)

3-element Vector{Int64}:
 1
 2
 3

In [70]:
∪(s1, s2) # \cup

3-element Vector{Int64}:
 1
 2
 3

In [71]:
s1 ∪ s2 # \cup

3-element Vector{Int64}:
 1
 2
 3

In [72]:
s1

2-element Vector{Int64}:
 1
 2

## `union!`

In [73]:
s1 = [1, 2]
s2 = [2, 3]
union!(s1, s2)

3-element Vector{Int64}:
 1
 2
 3

In [74]:
s1

3-element Vector{Int64}:
 1
 2
 3

## `intersect`

In [75]:
s1 = [1, 2]
s2 = [2, 3]
intersect(s1, s2)

1-element Vector{Int64}:
 2

In [76]:
∩(s1, s2) # \cap

1-element Vector{Int64}:
 2

In [77]:
s1 ∩ s2 # \cap

1-element Vector{Int64}:
 2

In [78]:
s1

2-element Vector{Int64}:
 1
 2

## `intersect!`

In [79]:
s1 = [1, 2]
s2 = [2, 3]
intersect!(s1, s2)

1-element Vector{Int64}:
 2

In [80]:
s1

1-element Vector{Int64}:
 2

## `setdiff`

In [81]:
s1 = [1, 2]
s2 = [2, 3]
setdiff(s1, s2)

1-element Vector{Int64}:
 1

In [82]:
s1

2-element Vector{Int64}:
 1
 2

## `!setdiff`

In [83]:
s1 = [1, 2]
s2 = [2, 3]
setdiff!(s1, s2)

1-element Vector{Int64}:
 1

In [84]:
s1

1-element Vector{Int64}:
 1

## `issubset`

In [85]:
s1 = [1, 2, 3, 4, 5]
s2 = [2, 3, 5];

In [86]:
issubset(s1, s2)

false

In [87]:
⊆(s1, s2) # \subseteq

false

In [88]:
s1 ⊆ s2 # \subseteq

false

In [89]:
⊈(s1, s2) # \nsubseteq 

true

In [90]:
s1 ⊈ s2 # \nsubseteq

true

In [91]:
issubset(s2, s1)

true

In [92]:
⊇(s1, s2) # \supseteq

true

In [93]:
s1 ⊇ s2 # \supseteq

true

In [94]:
⊉(s1, s2) # /nsupseteq

false

In [95]:
⊉(s1, s2) # /nsupseteq

false

## `issetequal`

In [96]:
s1 = [1, 2, 3]
s2 = [3, 2, 1];

In [97]:
issetequal(s1, s2)

true

In [98]:
(s1 ⊆ s1) && (s2 ⊆ s1)

true

## `isdisjoint`

In [99]:
s1 = [1, 2, 3]
s2 = [3, 4, 5];

In [100]:
isdisjoint(s1, s2)

false

In [101]:
isempty(s1 ∩ s2) # \cap

false

In [102]:
s1 = [1, 2, 3]
s2 = [4, 5, 6];

In [103]:
isdisjoint(s1, s2)

true

In [104]:
isempty(s1 ∩ s2) # \cap

true

## `Iterators.flatten`

In [105]:
v = [1, 2, [3, 4], 5, 6, [7, 8]]

6-element Vector{Any}:
 1
 2
  [3, 4]
 5
 6
  [7, 8]

In [106]:
collect(Iterators.flatten(v))

8-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8

## `push!`

In [107]:
vec = [1, 2, 3]
push!(vec, 4)
vec

4-element Vector{Int64}:
 1
 2
 3
 4

In [108]:
vec = [1, 2, 3]
push!(vec, 4, 5)
vec

5-element Vector{Int64}:
 1
 2
 3
 4
 5

## `pushfirst!`

In [109]:
vec = [1, 2, 3]
pushfirst!(vec, 4, 5)
vec

5-element Vector{Int64}:
 4
 5
 1
 2
 3

## `append!`

In [110]:
vec = [1, 2, 3]
append!(vec, [4, 5, 6])
vec

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [111]:
vec = [1, 2, 3]
append!(vec, [4, 5, 6], [7, 8, 9])
vec

9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

## `pop!`

In [112]:
vec = [1, 2, 3]
pop!(vec)

3

In [113]:
vec

2-element Vector{Int64}:
 1
 2

## `popfirst!`

In [114]:
vec = [1, 2, 3]
popfirst!(vec)

1

In [115]:
vec

2-element Vector{Int64}:
 2
 3

## `popat!`

In [116]:
vec = [10, 20, 30]
popat!(vec, 2)

20

In [117]:
vec

2-element Vector{Int64}:
 10
 30

## `insert!`

In [118]:
vec = Any[1:6;]
insert!(vec, 3, "here")
vec

7-element Vector{Any}:
 1
 2
  "here"
 3
 4
 5
 6

## `keepat!`

In [119]:
vec = [25, 30, 35, 40, 45, 50]
keepat!(vec, [2, 3, 4])
vec

3-element Vector{Int64}:
 30
 35
 40

## `deleteat!`

In [120]:
vec = [50, 40, 30, 20, 10];

In [121]:
deleteat!(vec, 3)
vec

4-element Vector{Int64}:
 50
 40
 20
 10

In [122]:
deleteat!(vec, 3)
vec

3-element Vector{Int64}:
 50
 40
 10

## `splice!`

In [123]:
vec = collect(10:10:70)

7-element Vector{Int64}:
 10
 20
 30
 40
 50
 60
 70

In [124]:
splice!(vec, 4)

40

In [125]:
vec

6-element Vector{Int64}:
 10
 20
 30
 50
 60
 70

In [126]:
splice!(vec, [4, 5, 6])
vec

3-element Vector{Int64}:
 10
 20
 30

In [127]:
splice!(vec, 1, -20)
vec

3-element Vector{Int64}:
 -20
  20
  30

In [128]:
splice!(vec, 1, [-30, -20, 0, 10])
vec

6-element Vector{Int64}:
 -30
 -20
   0
  10
  20
  30

## `prepend!`

In [129]:
vec = [9, 10]

2-element Vector{Int64}:
  9
 10

In [130]:
prepend!(vec, 7, 8)

4-element Vector{Int64}:
  7
  8
  9
 10

In [131]:
prepend!(vec, [5, 6])

6-element Vector{Int64}:
  5
  6
  7
  8
  9
 10

In [132]:
prepend!(vec, [1, 2], [3, 4])

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

## `delete!`

In [133]:
my_dict = Dict("a"=>10, "b"=>20, "c"=>30)

Dict{String, Int64} with 3 entries:
  "c" => 30
  "b" => 20
  "a" => 10

In [134]:
delete!(my_dict, "b")
my_dict

Dict{String, Int64} with 2 entries:
  "c" => 30
  "a" => 10

In [135]:
delete!(my_dict, "no_valid_key")
my_dict

Dict{String, Int64} with 2 entries:
  "c" => 30
  "a" => 10

In [136]:
[1:6;]

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

## `Pair`

In [137]:
a = "Julia" => "Romeo"

"Julia" => "Romeo"

In [138]:
typeof(a)

Pair{String, String}

In [139]:
a.first

"Julia"

In [140]:
for v in a
    println(v)
end

Julia
Romeo


## `StepRange`

In [141]:
collect(StepRange(1, Int8(2), 10))

5-element Vector{Int64}:
 1
 3
 5
 7
 9

In [142]:
typeof(1:2:9)

StepRange{Int64, Int64}

In [143]:
collect(1:2:9)

5-element Vector{Int64}:
 1
 3
 5
 7
 9

## `UnitRange`

In [144]:
collect(UnitRange(2.3, 6.7))

5-element Vector{Float64}:
 2.3
 3.3
 4.3
 5.3
 6.3

In [145]:
typeof(1:10)

UnitRange{Int64}

## `LinRange`

In [146]:
LinRange(0, 1, 5)

5-element LinRange{Float64, Int64}:
 0.0, 0.25, 0.5, 0.75, 1.0

In [147]:
LinRange(1.0, 2.5, 4)

4-element LinRange{Float64, Int64}:
 1.0, 1.5, 2.0, 2.5

In [148]:
LinRange(1, 5, 6)

6-element LinRange{Float64, Int64}:
 1.0, 1.8, 2.6, 3.4, 4.2, 5.0

## `range`

Compared to using `range`, directly constructing a `LinRange` should have less overhead but won't try to correct for floating point errors.

In [149]:
collect(range(-0.1, 0.3, length=5))

5-element Vector{Float64}:
 -0.1
  0.0
  0.1
  0.2
  0.3

In [150]:
collect(LinRange(-0.1, 0.3, 5))

5-element Vector{Float64}:
 -0.1
 -1.3877787807814457e-17
  0.09999999999999999
  0.19999999999999998
  0.3

## `step`

In [151]:
step(1:10)

1

In [152]:
step(1:2:10)

2

In [153]:
step(2.5:0.3:10.9)

0.3

## `isempty`

In [154]:
isempty([])

true

In [155]:
isempty(())

true

In [156]:
isempty("")

true

In [157]:
isempty(1)

false

In [158]:
isempty([1, 2, 3])

false

## `empty!`

In [159]:
vec = [1, 2, 3]
empty!(vec)
vec

Int64[]

## `length`

In [160]:
length(5)

1

In [161]:
length([1, 2, 3, 4, 5])

5

In [162]:
length("Julia")

5

## `in`

In [163]:
3 in [1, 2, 3]

true

In [164]:
3 ∈ [1, 2, 3] # \in

true

In [165]:
'a' in "Julia"

true

In [166]:
!(3 in [1, 2, 3]) # not in

false

In [167]:
3 ∉ [1, 2, 3] # \notin

false

In [168]:
[1, 2, 3] ∌ 3 # \nni

false

## `indexin`

In [169]:
a = ['a', 'b', 'x', 'd', 'c'];
b = ['a', 'b', 'c'];

In [170]:
indexin(a, b)

5-element Vector{Union{Nothing, Int64}}:
 1
 2
  nothing
  nothing
 3

In [171]:
indexin(b, a)

3-element Vector{Union{Nothing, Int64}}:
 1
 2
 5

## `unique`

In [172]:
unique([1, 2, 2, 3, 3, 3])

3-element Vector{Int64}:
 1
 2
 3

In [173]:
unique(Real[1, 1.0, 2])

2-element Vector{Real}:
 1
 2

In [174]:
unique(x -> x^2, [5, -5, -10, 10, 99])

3-element Vector{Int64}:
   5
 -10
  99

In [175]:
a = [10, 10, 20, 50, 30, 40, 30]
i = unique(i -> a[i], eachindex(a))

5-element Vector{Int64}:
 1
 3
 4
 5
 6

In [176]:
a[i]

5-element Vector{Int64}:
 10
 20
 50
 30
 40

In [177]:
a[i] == unique(a)

true

## `unique!`

In [178]:
a = [10, 20, 20, 30, 30, 30]
unique!(a)
a

3-element Vector{Int64}:
 10
 20
 30

## `allunique`

In [179]:
allunique([1, 2, 3])

true

In [180]:
allunique([1, 2, 3, 2, 1])

false

In [181]:
allunique([1, 2, 3, missing])

true

In [182]:
allunique([1, 2, 3, missing, missing])

false

## `allequal`

In [183]:
allequal([1, 2, 3])

false

In [184]:
allequal([0, 0, 0])

true

## `reduce`

In [185]:
reduce(*, [2, 3, 4])

24

In [186]:
reduce(*, [2, 3, 4], init=-5)

-120

In [187]:
reduce(/, [30, 3, 2])

5.0

In [188]:
reduce(+, [1, 2, 3])

6

In [189]:
+(1, 2, 3)

6

In [190]:
reduce(∘, [tan, cos, sin]).([1, 2, 3]) # \circ

3-element Vector{Float64}:
 0.786357394978223
 0.7053391147354299
 1.523873017405459

In [191]:
[tan(cos(sin(i))) for i in 1:3]


3-element Vector{Float64}:
 0.786357394978223
 0.7053391147354299
 1.523873017405459

### `...` (The "splat" operator)

In [192]:
+(1, 2, 3)

6

In [193]:
my_list = [1, 2, 3]
+(my_list)

3-element Vector{Int64}:
 1
 2
 3

In [194]:
my_list = [1, 2, 3]
+(my_list...)

6

In [195]:
+(my_list, my_list)

3-element Vector{Int64}:
 2
 4
 6

In [196]:
my_list = [[1, 2, 3], [10, 20, 30], [100, 200, 300]]
+(my_list...)

3-element Vector{Int64}:
 111
 222
 333

In [197]:
my_list = [1, 2, 3]
+(my_list...) == reduce(+, my_list)

true

### `splat`

In [198]:
my_add = splat(+)

splat(+)

In [199]:
my_add([1, 2, 3])

6

In [200]:
map(splat(+), zip([1, 2, 3], [10, 20, 30]))

3-element Vector{Int64}:
 11
 22
 33

## `reshape`

In [201]:
a = reshape(Vector(1:16), (4, 4))

4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [202]:
a'

4×4 adjoint(::Matrix{Int64}) with eltype Int64:
  1   2   3   4
  5   6   7   8
  9  10  11  12
 13  14  15  16

## `argmin`, `argmax`

In [203]:
argmin([10, 8, 6, 4, 2])

5

In [204]:
argmin([10, 8, 6, 4, 2, missing])

6

In [205]:
argmax([10, 8, 6, 4, 2])

1

In [206]:
argmin([10, 8, 6, 4, 2, missing])

6

In [207]:
f(x)::Float64 = 10 / x

f (generic function with 1 method)

In [208]:
a = collect(-5:2:5)

6-element Vector{Int64}:
 -5
 -3
 -1
  1
  3
  5

In [209]:
f.(a)

6-element Vector{Float64}:
  -2.0
  -3.3333333333333335
 -10.0
  10.0
   3.3333333333333335
   2.0

In [210]:
argmin(f, a)

-1

In [211]:
argmax(f, a)

1

## `all`

In [212]:
all([true, true, true])

true

In [213]:
all([true, true, false])

false

## `any`

In [214]:
any([true, true, true])

true

In [215]:
any([true, true, false])

true

In [216]:
any([false, false, false])

false

## `count`

In [217]:
count('a', "Julia language")

3

In [218]:
count(r"a(.)a", "cabacabac", overlap=true)

3

In [219]:
count(r"a(.)a", "cabacabac")

2

## `foreach`

In [220]:
a = [2, 3, 4]
b = Int[];

In [221]:
foreach(x -> push!(b, x^2), a)


## `first`, `last`

In [222]:
first([10, 20, 30])

10

In [223]:
first([10, 20, 30], 2)

2-element Vector{Int64}:
 10
 20

In [224]:
last([10, 20, 30])

30

In [225]:
last([10, 20, 30], 2)

2-element Vector{Int64}:
 20
 30

## `front`, `tail`

In [226]:
Base.front((10, 20, 30))

(10, 20)

In [227]:
Base.tail((10, 20, 30))

(20, 30)

## `collect`

In [228]:
collect(1:5)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [229]:
[x for x in 1:5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

## `filter`

In [230]:
a = collect(10:20);

In [231]:
filter(isodd, a)

5-element Vector{Int64}:
 11
 13
 15
 17
 19

In [232]:
filter(x -> x>15, a)

5-element Vector{Int64}:
 16
 17
 18
 19
 20

## `replace`

In [233]:
replace([1, 2, 1, 3, 1, 4, 1, 5], 1=>-1, 2=>-2, 3=>-3)

8-element Vector{Int64}:
 -1
 -2
 -1
 -3
 -1
  4
 -1
  5

In [234]:
replace([1, 2, 1, 3, 1, 4, 1, 5], 1=>-1, 2=>-2, 3=>-3, count=2)

8-element Vector{Int64}:
 -1
 -2
  1
  3
  1
  4
  1
  5

In [235]:
replace(x -> isodd(x) ? 2x : x, [1, 2, 3, 4])

4-element Vector{Int64}:
 2
 2
 6
 4

## `fieldcount`, `fieldnames`, `hasfield`, `getfield`

In [236]:
struct rectangle
    length::Number
    width::Number
end

In [237]:
fieldcount(rectangle)

2

In [238]:
fieldnames(rectangle)

(:length, :width)

In [239]:
hasfield(rectangle, :width)

true

In [240]:
my_rectangle = rectangle(4.0, 2.0)

rectangle(4.0, 2.0)

In [241]:
getfield(my_rectangle, :width)

2.0

In [242]:
getfield(my_rectangle, 1)

4.0

## `propertynames`, `hasproperty`, `getproperty`

In [243]:
struct rectangle
    length::Number
    width::Number
end

In [244]:
my_rectangle = rectangle(4.0, 2.0)

rectangle(4.0, 2.0)

In [245]:
propertynames(my_rectangle)

(:length, :width)

In [246]:
hasproperty(my_rectangle, :width)

true

In [247]:
hasproperty(my_rectangle, :radius)

false

In [248]:
getproperty(my_rectangle, :length)

4.0

In [249]:
getproperty(my_rectangle, :length) === my_rectangle.length

true

In [250]:
getproperty(my_rectangle, :length) === getfield(my_rectangle, :length)

true

## `isdefined`

In [251]:
isdefined(Base, :sum)

true

In [252]:
isdefined(Base, :fake)

false

In [253]:
isdefined(Base, :NonExistentMethod)

false

In [254]:
a = 1//3

1//3

In [255]:
isdefined(a, 2)

true

In [256]:
getfield(a, 2)

3

## `hasmethod`

In [257]:
hasmethod(+, Tuple{Int, Float64})

true

In [258]:
+(1, 2.3)

3.3

In [259]:
# can check keyword arguments too
hasmethod(range, Tuple{Int}, (:stop, :step))

true

## `oftype`

In [260]:
oftype(1.23, 10)

10.0

## `widen`

In [261]:
x = Int16(10)
x = widen(x)

10

In [262]:
typeof(x)

Int32

In [263]:
x = Int8(1)
while !isa(x, BigInt)
    x = widen(x)
    println(typeof(x))
end
    

Int16
Int32
Int64
Int128
BigInt


## `ismutable`, `isimmutable`

In [264]:
ismutable(1)

false

In [265]:
ismutable("Mutable")

true

In [266]:
ismutable([1, 2, 3])

true

In [267]:
isimmutable((1, 2, 3))

true

## `isstructtype`

In [268]:
struct rectangle
    length::Number
    width::Number
end

In [269]:
isstructtype(rectangle)

true

## `sizeof`

In [270]:
sizeof([10, 20, 30])

24

In [271]:
sizeof(1:1000)

16

In [272]:
sizeof(collect(1:1000))

8000

## `nothing`, `isnothing`

In [273]:
n = nothing

In [274]:
typeof(n)

Nothing

In [275]:
isnothing(n)

true

In [276]:
isnothing("")

false

## `|>` (infix operator)

In [277]:
16 |> sqrt

4.0

In [278]:
[2, 3, 5] |> sum |> inv

0.1

In [279]:
f1(x) = x+2
f2(x) = x^2
f3(x) = x-2;

In [280]:
f3(f2(f1(10)))

142

In [281]:
f1(10) |> f2 |> f3

142

### `∘` (function composition)

In [282]:
fruit = ["apple", "banana", "carrot"];

In [283]:
map(uppercase, fruit)

3-element Vector{String}:
 "APPLE"
 "BANANA"
 "CARROT"

In [284]:
map(first, fruit)

3-element Vector{Char}:
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)

In [285]:
# \circ
map(uppercase∘first, ["apple", "banana", "carrot"])

3-element Vector{Char}:
 'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)
 'B': ASCII/Unicode U+0042 (category Lu: Letter, uppercase)
 'C': ASCII/Unicode U+0043 (category Lu: Letter, uppercase)

In [286]:
reduce(∘, [tan, cos, sin]).([1, 2, 3]) == [tan(cos(sin(i))) for i in 1:3]

true