# JULIA

In [1]:
# versioninfo
versioninfo()

Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
Environment:
  JULIA_NUM_THREADS = 


## Basics

In [2]:
# Vector{Int64}
Vector{Int64}([1, 2, 3])

3-element Vector{Int64}:
 1
 2
 3

In [3]:
# Vector{Int64} - short syntax
Int64[1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [4]:
# Vector{Int64} - short syntax (type based on element types)
[1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [5]:
# Vector{Int64} - short syntax
[1:3;]

3-element Vector{Int64}:
 1
 2
 3

In [6]:
# Empty vector
Vector{Int8}()

Int8[]

In [7]:
# Empty vector - short syntax
vec = Int8[]

Int8[]

In [8]:
# Push one single element
push!(vec, 10)

1-element Vector{Int8}:
 10

In [9]:
# Append multiple elements
append!(vec, [20, 30, 40, 50])

5-element Vector{Int8}:
 10
 20
 30
 40
 50

In [10]:
# Pop last element
pop!(vec)
vec

4-element Vector{Int8}:
 10
 20
 30
 40

In [11]:
# Push element at front
pushfirst!(vec, -10)

5-element Vector{Int8}:
 -10
  10
  20
  30
  40

In [12]:
# Pop element at front
popfirst!(vec)

-10

In [13]:
# vec
vec

4-element Vector{Int8}:
 10
 20
 30
 40

In [14]:
# Insert value at position
insert!(vec, 3, -25)

5-element Vector{Int8}:
  10
  20
 -25
  30
  40

### Statistics

### `Base.jl`

In [15]:
# Vector
vec = collect(1:9)

9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [16]:
# Sum
sum(vec)

45

In [17]:
# Which
@which sum

Base

### `Statistics.jl`

https://docs.julialang.org/en/v1/stdlib/Statistics

In [18]:
using Statistics

#### `mean`

In [19]:
# vector
vec = collect(1:10);

In [20]:
# mean
mean(vec)

5.5

In [21]:
# which mean
@which mean

Statistics

In [22]:
# mean
Statistics.mean(vec)

5.5

In [23]:
# vector with missings
vec = [0, 1, 2, missing, 4, 5, missing, missing, 8, 9];

In [24]:
# mean
Statistics.mean(vec)

missing

In [25]:
# mean
Statistics.mean(skipmissing(vec))

4.142857142857143

#### `var`

In [26]:
# vector with missings
vec = [0, 1, 2, missing, 4, 5, missing, missing, 8, 9];

In [27]:
# Var
Statistics.var(vec)

missing

In [28]:
Statistics.var(skipmissing(vec))

11.80952380952381

#### `std`

In [29]:
# vector with missings
vec = [0, 1, 2, missing, 4, 5, missing, missing, 8, 9];

In [30]:
# std
Statistics.std(vec)

missing

In [31]:
# std
Statistics.std(skipmissing(vec))

3.4364987719368982

#### `median`

In [32]:
# vector with missings
vec = [0, 1, 2, missing, 4, 5, missing, missing, 8, 9];

In [33]:
# median
Statistics.median(vec)

missing

In [34]:
# median
Statistics.median(skipmissing(vec))

4.0

#### `quantile`

In [35]:
# vector with missings
vec = [0, 1, 2, missing, 4, 5, missing, missing, 8, 9];

In [36]:
# quantile
Statistics.quantile(skipmissing(vec), 0.5)

4.0

In [37]:
# quantile
Statistics.quantile(skipmissing(vec), [0, .25, .5, .75, 1])

5-element Vector{Float64}:
 0.0
 1.5
 4.0
 6.5
 9.0

## `zeros`, `ones` and `fill`

In [38]:
zeros(5)

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [39]:
ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [40]:
fill(π, 5)

5-element Vector{Irrational{:π}}:
 π = 3.1415926535897...
 π = 3.1415926535897...
 π = 3.1415926535897...
 π = 3.1415926535897...
 π = 3.1415926535897...

## Mixed types

In [41]:
A = [1, 2, missing]

3-element Vector{Union{Missing, Int64}}:
 1
 2
  missing

In [42]:
B = Vector{Union{Missing, Int64}}()

Union{Missing, Int64}[]

In [43]:
append!(B, [1, 2])

2-element Vector{Union{Missing, Int64}}:
 1
 2

In [44]:
push!(B, missing)

3-element Vector{Union{Missing, Int64}}:
 1
 2
  missing

In [45]:
C = Vector{Union{Int64, String}}()

Union{Int64, String}[]

In [46]:
append!(C, [10, "ten"])

2-element Vector{Union{Int64, String}}:
 10
   "ten"

In [47]:
push!(C, 10.0)

MethodError: MethodError: Cannot `convert` an object of type 
  Float64 to an object of type 
  Union{Int64, String}

Closest candidates are:
  convert(::Type{T}, !Matched::T) where T
   @ Base Base.jl:64


## Subsetting

### Index

In [48]:
my_vec = Vector{Int8}(collect(10:10:100))

10-element Vector{Int8}:
  10
  20
  30
  40
  50
  60
  70
  80
  90
 100

In [49]:
my_vec[begin:3]

3-element Vector{Int8}:
 10
 20
 30

In [50]:
my_vec[4:6]

3-element Vector{Int8}:
 40
 50
 60

In [51]:
my_vec[2:2:8]

4-element Vector{Int8}:
 20
 40
 60
 80

In [52]:
my_vec[7:end-1]

3-element Vector{Int8}:
 70
 80
 90

In [53]:
my_vec[end:-1:begin]

10-element Vector{Int8}:
 100
  90
  80
  70
  60
  50
  40
  30
  20
  10

### Value

In [54]:
my_vec = Vector{Int8}(collect(10:10:100))

10-element Vector{Int8}:
  10
  20
  30
  40
  50
  60
  70
  80
  90
 100

In [55]:
bv = my_vec.>=70

10-element BitVector:
 0
 0
 0
 0
 0
 0
 1
 1
 1
 1

In [56]:
my_vec[bv]

4-element Vector{Int8}:
  70
  80
  90
 100

In [57]:
my_vec[my_vec.<=20 .|| my_vec.>=80]

5-element Vector{Int8}:
  10
  20
  80
  90
 100

In [58]:
my_vec[my_vec.<=80 .&& my_vec.>=50]

4-element Vector{Int8}:
 50
 60
 70
 80

## Vector comprehension

In [59]:
[10i for i in 1:5] # Vector{Int64}(collect(10:10:50))

5-element Vector{Int64}:
 10
 20
 30
 40
 50

In [60]:
[i for i in 1:3 for j in 1:2]

6-element Vector{Int64}:
 1
 1
 2
 2
 3
 3

In [61]:
["Group $i" for i in 'A':'C' for j in 1:2]

6-element Vector{String}:
 "Group A"
 "Group A"
 "Group B"
 "Group B"
 "Group C"
 "Group C"

In [62]:
[i for i in 1:10 if i % 3 == 0]

3-element Vector{Int64}:
 3
 6
 9

In [63]:
[x % 2 == 0 ? -x : 10x for x in 1:5]

5-element Vector{Int64}:
 10
 -2
 30
 -4
 50

In [64]:
[x < y ? x : y for (x, y) in zip([2, 4, 6], [1, 5, 10])]

3-element Vector{Int64}:
 1
 4
 6

In [65]:
[
    begin
        #= think some complicated expression here =#
        if i ≤ 3
            x = 10i
        elseif i ≤ 7
            x = -(i^2)
        else
            x = 5i
        end
    end 
    for i in 1:10
]

10-element Vector{Int64}:
  10
  20
  30
 -16
 -25
 -36
 -49
  40
  45
  50

## Memory size

In [66]:
vec_a = Int8[]
append!(vec_a, 1:127)
Base.summarysize(vec_a)



167

In [67]:
vec_b = Int64[]
append!(vec_b, 1:127)
Base.summarysize(vec_b)

1056